info:
  app:
    name: MyApp
    description: My Test application for Jpa Repository
  author: smoker21
  purpose: demo & study
  gitbook: https://www.gitbook.com/book/smoker21/rancher-and-springboot/details
      
spring:
  application:
    name: MyJpaSample
  data:
    rest:
      base-path: api
    jpa:
      repositories:
        enabled: true
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
server:
  port: 9001 
    
logging:
  level:
    org: 
      hibernate:
        SQL: debug
  
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
---
spring:
  profiles: production
      
eureka:
  instance:
    hostname: ${hostname:localhost}
  client:
    service-url:
      defaultZone: http://${eurekaServer1}:${eurekaPort1:8761}/eureka,http://${eurekaServer2}:${eurekaPort2:8761}/eureka                